# Generated by Django 4.0.3 on 2022-05-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='labs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labID', models.IntegerField()),
                ('name', models.CharField(max_length=16)),
                ('fNum', models.IntegerField()),
                ('pcNum', models.IntegerField()),
                ('cap', models.IntegerField()),
                ('chairNum', models.IntegerField()),
                ('labStatus', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='PCs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcStatus', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
    ]
