# Generated by Django 4.0.3 on 2022-05-20 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labs',
            old_name='name',
            new_name='labName',
        ),
    ]
