# Generated by Django 4.0.3 on 2022-05-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_rename_name_labs_labname'),
    ]

    operations = [
        migrations.AddField(
            model_name='labs',
            name='bNum',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
