# Generated by Django 4.0.3 on 2022-05-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_remove_labs_bnum_remove_labs_cap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labs',
            name='labID',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
