# Generated by Django 4.0.3 on 2022-05-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_alter_labs_labid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcs',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pcs',
            name='labID',
        ),
        migrations.AddField(
            model_name='pcs',
            name='pcID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
