# Generated by Django 4.0.3 on 2022-05-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_remove_pcs_id_remove_pcs_labid_pcs_pcid'),
    ]

    operations = [
        migrations.AddField(
            model_name='labs',
            name='bNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='labs',
            name='cap',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='labs',
            name='chairNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='labs',
            name='fNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='labs',
            name='pcNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pcs',
            name='labID',
            field=models.IntegerField(default=0),
        ),
    ]
