# Generated by Django 4.0.3 on 2022-05-20 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_labs_bnum_labs_cap_labs_chairnum_labs_fnum_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='labs',
            new_name='lab',
        ),
        migrations.RenameModel(
            old_name='PCs',
            new_name='PC',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
