# Generated by Django 4.0.3 on 2022-05-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_rename_labs_lab_rename_pcs_pc_rename_users_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='pcID',
            field=models.IntegerField(default=0),
        ),
    ]
