# Generated by Django 4.0.3 on 2022-05-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_pc_id_alter_pc_pcid'),
    ]

    operations = [

        migrations.AlterField(
            model_name='lab',
            name='labID',
            field=models.IntegerField(default=0),
        ),
    ]
