# Generated by Django 4.0.4 on 2022-05-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_lab_id_pc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='labID',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
