# Generated by Django 4.0.3 on 2022-05-22 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_issue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='type',
            new_name='Type',
        ),
    ]
