# Generated by Django 4.0.3 on 2022-05-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_rename_type_issue_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
