# Generated by Django 4.0.3 on 2022-05-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_alter_pc_pcstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='labStatus',
            field=models.CharField(max_length=24),
        ),
    ]
